services:
  traefik:
    image: traefik:latest
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "81:80" # The HTTP port
      - "8081:8080" # The Dashboard port
      - "443:443"
    volumes:
      - "./config:/etc/traefik/"
      - "/var/run/docker.sock:/var/run/docker.sock"
