- name: "Ansible System Init"
  hosts: localhost
  connection: local
  become: false

  vars_files:
  - vars/main.yml
  - vars/packages.yml

  handlers:
  - name: import handlers
    import_tasks:
      file: "{{playbook_dir}}/handlers/notify.yml"

  pre_tasks:
  - include_tasks:
      file: "{{item}}"
    loop:
    - pre_tasks/get_start_time.yml
    - pre_tasks/ensure_folders.yml
    - pre_tasks/whoami.yml
    - pre_tasks/add_fonts.yml
    # roles:
    # - role: geerlingguy.docker
    #   become: true
    # ignore_errors: true

  tasks:
  - block:
    - name: package_install
      import_tasks: tasks/package_install.yml
      ignore_errors: true
      become: true

    ## Uncomment the below task if the old dotfiles repo eed to be cloned

    # - name: pull config repo
    #   git:
    #     repo: "{{ dotfile_git_repo }}"
    #     dest: "{{ home_folder }}/repos/dotfiles_old/"
    #     recursive: false
    #     version: master


    - name: Set roles
      set_fact:
        run_roles: "{{ default_roles | difference(exclude_roles | default([])) }}"
      tags:
      - always

    - name: Display roles
      debug:
        var: run_roles
      tags:
      - always

    - name: Apply Roles
      include_role:
        name: "{{item}}"
        apply:
          tags:
          - "{{item}}"
      with_items: "{{run_roles}}"
      tags:
      - always

  post_tasks:
  - include_tasks:
      file: "{{item}}"
    loop:
    - post_tasks/get_exec_time.yml

  - name: check for playbook failure
    debug:
      msg: "playbook failed. - {{ansible_failed['msg']}}"
    when: ansible_failed is defined
    notify:
    - ansible_notiffier

  - name: playbook_succes
    debug:
      msg: "playbook success"
    changed_when: true
    notify: ansible_notifier
    when: ansible_failed is not defined
