- name: Tmux | install Tmux
  homebrew:
    name: tmux
    state: present

- name: Tmux | link config file to home folder
  file:
    src: "{{playbook_dir}}/files/tmux/tmux.conf"
    path: "{{ ansible_user_dir }}/.tmux.conf"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    state: link
    force: true
  when: dry_run == false
